import type { Metadata } from "next";
import "@/app/globals.css";


export const metadata: Metadata = {
  title: "Unibank Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("render root layout 2")
  return ( 
       <section> {children}</section> 
  );
}
