import type { Metadata } from "next";
import "@/app/globals.css";
import { Open_Sans } from "next/font/google";
 export const metadata: Metadata = {
  title: "Zenith Online",
  description: "Generated by create next app",
};


const baseFont = Open_Sans({
  weight: ["400", "600", "800"],
  subsets: ["latin"],
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {  
  return (
    <html lang="en">
      <body className={`${baseFont.className}  antialiased bg-slate-50`}>
       {children} 
      </body>
    </html>
  );
}
