import type { Metadata } from "next";
import "@/app/globals.css";
import { Open_Sans } from "next/font/google";
import NavBarFragment from "@/core/page_builder/_partials/NavBarFragment";
import CMSSubSiteService from "@/core/services/CMSSubSiteService";
import { notFound } from "next/navigation";
import FooterFragment from "@/core/page_builder/_partials/FooterFragment";
export const metadata: Metadata = {
  title: "Zenith Online",
  description: "Generated by create next app",
};

const SUBSITE_SLUG = "business";

const baseFont = Open_Sans({
  weight: ["400", "600", "800"],
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentSite = await CMSSubSiteService.getBySlug(SUBSITE_SLUG);

  if (!currentSite) {
    notFound();
  }

  return (
    <html lang="en">
      <body className={`${baseFont.className}  antialiased bg-slate-50`}>
        {currentSite?.navBar && (
          <NavBarFragment
            {...currentSite?.navBar}
            selected={currentSite?.navBar?.sub_sites.findIndex(
              (i) => i?.slug == SUBSITE_SLUG
            )}
          />
        )}
        {children}

        {currentSite?.footer && (
           <FooterFragment {...currentSite.footer} />
        )}
      </body>
    </html>
  );
}
