import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Bot } from "lucide-react";
import CookiesNotice from "@/components/CookiesNotice";

const geistSans = Open_Sans({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "iBanca Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}  antialiased bg-slate-50`}>
        {children}

        <div className="fixed bottom-12 right-12 z-50">
          <Button className="w-16 h-16 rounded-full">
            <div className="min-w-34 min-h-34">
              <Bot size="34" />
            </div>
          </Button>
        </div>

        <CookiesNotice />
      </body>
    </html>
  );
}
