import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import CookiesNotice from "@/components/CookiesNotice";
import Footer from "@/components/Footer";
import NavBar from "@/components/Navbar";
import PhoneCallLeadButton from "@/components/PhoneCallLeadButton";
import ChatBotBox from "@/components/ChatBotBox";
import { menuSettings } from "@/components/Navbar/dataInit";
import { getClient } from "./core/lib/graphqlClient";
import DefaultGlobalsQuery from "./core/page_builder/queries/globals";

const baseFont = Open_Sans({
  weight: ["400", "600", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Unibank Online",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { data } = await getClient().query({
    query: DefaultGlobalsQuery,
  });

  console.log("layout", data);

  return (
    <html lang="en">
      <body className={`${baseFont.className}  antialiased bg-slate-50`}>
        <NavBar selectedSite={0} menu={menuSettings} />
        <PhoneCallLeadButton />
        {children}
        <ChatBotBox />
        <CookiesNotice />
        <Footer /> 
      </body>
    </html>
  );
}
