import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { Bot } from "lucide-react";
import CookiesNotice from "@/components/CookiesNotice";
import Footer from "@/components/Footer";
import NavBar from "@/components/Navbar";
import PhoneCallLeadButton from "@/components/PhoneCallLeadButton";

const geistSans = Open_Sans({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "iBanca Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className}  antialiased bg-slate-50`}>
        
      <NavBar />
      <PhoneCallLeadButton />
      
        {children}

        <div className="fixed bottom-2 right-2 lg:bottom-10 lg:right-10 z-50">
          <Button className="w-16 h-16 rounded-full bg-orange-500 hover:text-white text-black">
            <div className="min-w-34 min-h-34">
              <Bot size="54" className="" />
            </div>
          </Button>
        </div>

        <CookiesNotice />
        <Footer />
      </body>
    </html>
  );
}
